name: Hugo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

jobs:

  hugo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: bindl-dev/bindl@main
      with:
        install-dir: bin
    
    - name: Generate HTML 
      run: make hugo

    - uses: chainguard-dev/actions/nodiff@main
      with:
        fixup-command: "make hugo" 

  bindl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: bindl-dev/bindl@main
      with:
        install-dir: bin

    - run: bindl sync

    - uses: chainguard-dev/actions/nodiff@main
      with:
        fixup-command: "bindl sync"